# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: miaohongxuan の Windows 98
baseurl: "http://blog.on-high.top/windows98/" # the subpath of your site, e.g. /blog
url: "http://blog.on-high.top/windows98" # http://www.54gaozhe.com # the base hostname & protocol for your site

# https://jekyllrb.com/docs/pagination/
paginate: 5
# specify the destination of the pagination pages
paginate_path: "/windows98/:num"

excerpt_separator:  '<!-- more -->'

plugins: [jekyll-paginate, kramdown]
# Build settings
# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
